version: '3.8'

services:
  db:
    container_name: sijak_db
    hostname: ${SIJAK_DB_HOST}
    image: bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: ${SIJAK_DB_NAME}
      POSTGRESQL_USERNAME: ${SIJAK_DB_USERNAME}
      POSTGRESQL_PASSWORD: ${SIJAK_DB_PASSWORD}
      POSTGRESQL_PORT_NUMBER: ${SIJAK_DB_PORT}
    ports:
      - "${SIJAK_DB_PORT}:${SIJAK_DB_PORT}"
